### ISSUE TITLE
User profiles

### ISSUE THREAD

**Issue by christickner** [phpmentoring/testapp#1]
some profile information, including:
- tagging myself with subjects I want to learn / teach
- seeking: a mentor, an apprentice, or both
- status: active / not active (actively seeking mentor/apprentice, to show up in a search or not)

**Comment by christickner** [comment]
I'll start on this issue this week

**Comment by christickner** [comment]
We're most of the way there on this one. I think we're just missing the "status" (active/not-active), which should be reflected in search.

**Comment by dragonmantank** [comment]
These are all set, so closing
