### ISSUE TITLE
Hamburger menu inoperative

### ISSUE THREAD

**Issue by RileyMajor** [phpmentoring/testapp#10]
The hamburger menu appears at lower page widths, but nothing happens when you click on it.

**Comment by RileyMajor** [comment]
This could have something to do with these missing javascript files:

[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (bootstrap.min.js, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (modernizr-2.8.3-respond-1.4.2.min.js, line 0)

**Comment by dragonmantank** [comment]
This was due to the 404s. Corrected with 61667e977474afe6bbecfc7ceab48b7ea9cff8c8
