### ISSUE TITLE
"Find an apprentice" link in Inbox leads to page that indicates mentors cannot be found.

### ISSUE THREAD

**Issue by jmichaelward** [phpmentoring/testapp#100]
I haven't been 'round these parts in awhile, but I understand the "Search Apprentices" functionality has been removed since last I peeked at this repo. 

On http://php-mentoring.org, after I log in, I'm given the option to view my inbox. On the inbox page, there is another call to action to "find an apprentice." Clicking on that link takes me to the search page.

The search page has some items marked correctly - e.g., the heading says "PHP Apprentices", and the text by the search bar says "Type in a tag to search for an apprentice. Right now this only supports one tag." However, below it, there is an error message that indicates the system couldn't find any members, and remnant template tags are rendered.

If the "Find an Apprentice" functionality has been removed, we should strip out the call to action altogether, but also remove the conditional logic for `apprenticeTags` in `public/js/main.js`. Perhaps that's being kept for a reason - future implementation? In either case, we should ensure that users cannot get to this page that contains incomplete functionality.

**Comment by jmichaelward** [comment]
<img width="1327" alt="screen shot 2017-01-23 at 10 55 23 pm" src="https://cloud.githubusercontent.com/assets/1407326/22234724/f0e14108-e1bf-11e6-83fa-586d8b9664bd.png">

Screenshot attached.

**Comment by dragonmantank** [comment]
The feature was planned but never fully finished, so we removed the links as it was built in tandem with the mentor search. 

Can you send a screenshot of where the link is?

**Comment by sprunka** [comment]
![screenshot from 2017-02-03 20 00 39](https://cloud.githubusercontent.com/assets/810961/22614047/9b7e5ce8-ea4b-11e6-998d-1ad515f6a8f1.png)

**Comment by sprunka** [comment]
To be clear, the fix for this bug is removing the link... only? or is there some code that should be refactored away as well? I'll claim this bug either way...

**Comment by sprunka** [comment]
Resolved with PR #101

**Comment by dragonmantank** [comment]
That explains why I couldn't see it, I had conversations.

PR was merged. Thanks!

**Comment by sukima** [comment]
@dcousineau [The Wiki - How-To page](https://github.com/phpmentoring/phpmentoring.github.com/wiki/HOWTO) also points to the incorrect link:

![phpscreenshot](https://user-images.githubusercontent.com/70075/30438427-35741ade-993f-11e7-9d11-997e9e841695.png)

**Comment by dragonmantank** [comment]
Thanks for noticing this. That link has been removed from the wiki :)
