### ISSUE TITLE
Email Notifications Not Working

### ISSUE THREAD

**Issue by geggleto** [phpmentoring/testapp#105]
Hello,

I have not received a notification email since 2016-12-06 despite receiving 3 messages on the php-mentoring website.

**Comment by svpernova09** [comment]
in the last 30 days we've sent 33 emails through the sparkpost account. I think @dragonmantank would have to check to ensure the config hasn't changed. He and I have access to the Sparkpost account we're using.

**Comment by dragonmantank** [comment]
Did a test message to @svpernova09 which seems to have gone through, and confirmed on Spark that messages are flowing out.

My guess is they got gobbled up by a SPAM filter. Google especially likes to do that every so often, no matter how much we try and be good mail senders.
