### ISSUE TITLE
Syntax Highlighting in Messages

### ISSUE THREAD

**Issue by dragonmantank** [phpmentoring/testapp#16]
Makes code easier to read if mentors/apprentices are passing that back and forth

**Comment by christickner** [comment]
Started this here (https://github.com/phpmentoring/testapp/commit/8cb6bb3b93e0d18234251f9840e2d7d40a9d6720) - just need to do some work on the editor:
1. I propose we have tabs like github for "Edit" and "Preview"
2. Clicking the tab uses ajax to get the preview from the server and display it

Markdown and syntax highlighting both work on the profile page, too, for users, so we'll have to edit the textareas to be the same on the edit profile page as in messages.

If anyone wants to do a javascript rendering for a live preview, then thats a decent option too :)

**Comment by christickner** [comment]
should be resolved here: https://github.com/phpmentoring/webapp/pull/29
