### ISSUE TITLE
migration issue

### ISSUE THREAD

**Issue by christickner** [phpmentoring/testapp#18]
I just did a fresh install on the new VM config.... and I got:

"SQLSTATE[42S22]: Column not found: 1054 Unknown column 'imageUrl' in 'field list'"

I don't see a migration for the profile image stuff

**Comment by dragonmantank** [comment]
Which page did you see it on? We added an imageUrl field that is generated from a github URL so we don't store it, so obviously we don't want to store it in the DB.
