### ISSUE TITLE
Profile images are huge

### ISSUE THREAD

**Issue by asgrim** [phpmentoring/testapp#26]
![image-huge](https://cloud.githubusercontent.com/assets/496145/7855299/48b2cad6-0518-11e5-92f8-9cc2aae29746.png)

I'm using Chrome 43.0.2357.81 (64-bit) on Ubuntu 15.04.

**Comment by christickner** [comment]
thanks for reporting this @asgrim  !

Should be fixed in 456ad46aa7ace606506759167c514fdd4f71b448
