### ISSUE TITLE
github "fork me" banner blocks login nav

### ISSUE THREAD

**Issue by christickner** [phpmentoring/testapp#30]
This may change in future designs, but at the moment the login button on the far right of the top bar can be completely blocked by the github banner.

![image](https://cloud.githubusercontent.com/assets/501390/8357895/5738869e-1b2b-11e5-8182-1bbf6ee25271.png)

**Comment by tristanbailey** [comment]
Would you mind me implementing this css only version of this, image. Advantage being, apart from no image to load, that the css allows you to click in the "space around it", so you could click on the login or the mobile menu.

http://simonwhitaker.github.io/github-fork-ribbon-css/

**Comment by tristanbailey** [comment]
I have been developing websites for 13+ years and worked though companies to Senior Dev. Middle/Backend developer and full stack team lead (PHP, MySQL, [Laravel, Slim, Joomla, EE, WP, Magento], DevOps, Agile). Moved to Freelance Developer about 4 years ago, and work with agencies and clients, on medium to large travel and eCommerce sites. When writing fresh projects I use Laravel or SlimPHP but often work on existing systems and integrations.
Happy to mentor others about php, full stack development, working with teams, coding, freelance work, DevOps, analytics, strategy etc

**Comment by dragonmantank** [comment]
Nope, feel free! I'm also open to moving it to a different corner.

**Comment by tristanbailey** [comment]
Added the PR here: https://github.com/phpmentoring/webapp/pull/39

**Comment by dragonmantank** [comment]
This is all finished and #39 was merged in. Closing!
