### ISSUE TITLE
Mentors page lists tags for Apprentices

### ISSUE THREAD

**Issue by jmichaelward** [phpmentoring/testapp#32]
If a user selects to be a Mentor, the system will currently attempt to list any tags that user has entered for the Apprentice role (displaying empty markup if no Apprentice tags were entered, or displaying the term tags for Apprentice if any are found).

Line 25 of the mentors.twig file attempts to iterate through tag in mentor.apprenticeTags. This should be updated to mentor.mentorTags. I uploaded a fix (here: https://github.com/jmichaelward/webapp/tree/hotfix/mentors-filter), though I understand it may not be relevant if we're moving away from Angular.

**Comment by dragonmantank** [comment]
We're keeping Angular, so go ahead and submit a PR for this.

**Comment by jmichaelward** [comment]
Perfect. Submitted.

**Comment by dragonmantank** [comment]
Closing. Fixed with b34e6e7dba1cf723c98b13090a0752441b3fe649
