### ISSUE TITLE
Call for Concerns about Launching without Apprentice Searching/Matching

### ISSUE THREAD

**Issue by dragonmantank** [phpmentoring/testapp#37]
On the #phpmentoring, it was brought up to possibly launch this without the need for searching apprentices, or having an official matching of Apprentices and Mentors. This is functionality that can be added at a later time, but there is a larger need to get this out to make it easier for apprentices to find mentors, especially considering the state of the wiki.

I'm putting up a vote for releasing the app with:
- The ability for anyone to sign up via Github
- The ability for users to message each other
- A Mentor searching page
- Mentors to flag themselves as mentors
- Mentors to add various things they want to teach
- Mentors to add a profile text for people to read on the mentors page

The above is all currently working in the development version, which we can push live. All the apprentice related code will just be deactivated so we can turn it back on at a later date.

I will be taking concerns against doing this release until 2015-07-30 16:00 UTC (12pm eastern). If you think we should wait or have any concerns or comments, please leave a comment below.

**Comment by manchuck** [comment]
2015-07-30 16:00 UTC (4pm eastern) is not 4PM eastern

**Comment by dragonmantank** [comment]
@manchuck hush, I fixed it!

**Comment by akrabat** [comment]
FWiW, I'm in favour of releasing as described above.

**Comment by GeeH** [comment]
:+1:

**Comment by auroraeosrose** [comment]
SHIP IT :ship:

**Comment by christickner** [comment]
I think we should merge #35 so people can be notified when they get a message. After that I am :+1:

**Comment by dragonmantank** [comment]
@christickner I thought I merged that, I'll get that in today.

**Comment by tristanbailey** [comment]
Ship it. I just got a mentee request from the Dev site. (Might be because all the quality candidates put in test bios)

**Comment by dragonmantank** [comment]
Overwhelming vote is "Ship it", so that's what we'll be doing! 

Thanks everyone!
