### ISSUE TITLE
send email notifications by default

### ISSUE THREAD

**Issue by christickner** [phpmentoring/testapp#43]
#35 allows you to recieve an email notificaiton if you get a message, but you have to opt in to this because it is turned off by default.

I think we'd be better off with a default ON, and you'd need to opt-out.

What do you all think?

**Comment by dragonmantank** [comment]
I'm fine with it being opt-out, it makes sense that people don't want to check the site every day

**Comment by christickner** [comment]
I've made it such that new registrations will have notifications turned on by default .However there are dozens of accounts on the site already, and it's likely many of them didn't get a chance to see the setting. I think we should do a one-time DB update to turn notifications to "on" for everyone, and they can login to opt out if necessary.  I think overall most poeple will want this enabled anyway. I'll make a PR and we can discuss it.

@dragonmantank do you have any strong feelings against doing a DB update to turn this setting on for everyone?

**Comment by christickner** [comment]
This has been merged. Thanks. Closing issue.
