### ISSUE TITLE
Mentor tags flow into content on 'Search Mentors' page

### ISSUE THREAD

**Issue by jmichaelward** [phpmentoring/testapp#45]
I think @elazar fixed this issue on the individual mentor pages already, by breaking up the tags and keeping them within the flow of content. We need to apply these same styles to the 'Search Mentors' page. 

Example screenshot attached.

<img width="1163" alt="screen shot 2015-08-14 at 9 53 16 am" src="https://cloud.githubusercontent.com/assets/1407326/9276556/52f7e032-426a-11e5-9020-07f2137fd5f9.png">

**Comment by elazar** [comment]
Yup. See #42.

**Comment by christickner** [comment]
This should now be fixed and will be included in our next update https://github.com/phpmentoring/webapp/commit/6e5b817192f6abf45f614d0ce0442bb41fbe1b9d
