### ISSUE TITLE
SSL connection

### ISSUE THREAD

**Issue by tdutrion** [phpmentoring/testapp#51]
I think the website connection should be secured with an SSL certificate, as people may be disclosing relatively private information on their lives in private messages and may be doing that from work if their bosses are aware of the advantages of being mentored.

I can provide a [Comodo Positive SSL for 3 years from Namecheap](https://www.namecheap.com/security/ssl-certificates/comodo/positivessl.aspx) if needed (paid by my company, no logo display required or anything).

**Comment by dragonmantank** [comment]
That would be a great addition. There's no specific reason to not run with SSL, so adding it is only a plus.

**Comment by tdutrion** [comment]
Just bought a 3 years certificate for the project on namecheap. I will need you to provide the details required to configure it.

Can you add me on twitter so we can complete this by exchanging DMs (or any other means that suits you, I'm also on keybase.io and can invite you there).

**Comment by christickner** [comment]
Thanks @tdutrion ! This is great!

**Comment by dragonmantank** [comment]
@tdutrion Followed you on Twitter :)

**Comment by tdutrion** [comment]
```
The identity of this website has been verified by COMODO ECC Domain Validation Secure Server CA 2. No Certificate Transparency information was supplied by the server.
```

I guess this issue has been solved then!
