### ISSUE TITLE
Add github-username or github-URL to the API-information

### ISSUE THREAD

**Issue by heiglandreas** [phpmentoring/testapp#53]
To get more information for a user from github it would be helpful to have the github-username available as the API-Endpoint for github to get user-infos is `https://api.github.com/user/[username]`. 

It is possible to get that URL using the already in the API provided `githubUid` but that will then require first a call to `https://api.github.com/users?since=[githubUid-1]&per_page=1` which will then return me the username and the url for the user-infos.

As that means 2 calls against the API instead of one call the rate-limit is hit much earlier :frowning:

**Comment by svpernova09** [comment]
Looks like changes have been merged? Is there still anything pending for this issue?

**Comment by dragonmantank** [comment]
Nope, this should be closed. So closing!

**Comment by heiglandreas** [comment]
Thanks for closing!
