### ISSUE TITLE
consistent naming in the API

### ISSUE THREAD

**Issue by heiglandreas** [phpmentoring/testapp#54]
Currently the naming of the returned keys is currently inconsistent camelCased **and** snake_cased (`imageUrl`, `isEnabled` opposed to `profile_markdown`).

wouldn't it be nicer to have that in one fashion?

**Comment by christickner** [comment]
This is now fixed here: 845fcb9d54e6c101cf32fe8fee54d80209dc5bc3

Thanks for reporting!
