### ISSUE TITLE
Mentors that also apply for apprenticeship aren't included in the mentor-list

### ISSUE THREAD

**Issue by heiglandreas** [phpmentoring/testapp#56]
The mentors-list that can be retrieved via http://app.phpmentoring.org/api/v0/mentors does not include those mentors that also applied as mentees.

**Comment by dragonmantank** [comment]
Can you give me some specific examples?

On my account, I tested the following:
- Only 'I want to be a mentor' selected - Showed up in list
- Both 'I want to be a mentor' and 'I want to be an apprentice' selected - Showed up in list
- Only 'I want to be an apprentice' selected - Did not show up
- Both 'I want to be a mentor' and 'I want to be an apprentice' not selected - Did not show up

**Comment by heiglandreas** [comment]
Sorry, I can't reproduce it anymore. Forget about it. It seems to work as expected!
