### ISSUE TITLE
The vagrantbox seems not to be working

### ISSUE THREAD

**Issue by PurpleBooth** [phpmentoring/testapp#61]
```
Billies-MacBook-Pro-2:webapp billie$ VBoxManage --version
5.0.8r103449
```

```
Billies-MacBook-Pro-2:webapp billie$ vagrant --version
Vagrant 1.7.4
```

```
Billies-MacBook-Pro-2:webapp billie$ vagrant destroy && vagrant up
==> default: VM not created. Moving on...
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'puphpet/debian75-x64'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'puphpet/debian75-x64' is up to date...
==> default: Setting the name of the VM: webapp_default_1446275070140_16109
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 80 => 8080 (adapter 1)
    default: 1080 => 1080 (adapter 1)
    default: 3306 => 7512 (adapter 1)
    default: 22 => 2222 (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
    default: 
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default: 
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
```

**Comment by dragonmantank** [comment]
This is actually a problem with puphpet and newer installs of vagrant where the key doesn't get added correctly and isn't specific to our box. Vagrant now tries to detect the old insecure key, and for some reason with puphpet boxes it _always_ thinks the insecure key is there and messes up.

When this happens, you have to get the text from `puphpet/files/dot/ssh/id_rsa.pub` and add it to the `~/.ssh/authorized_keys2` file for the vagrant user.

In another window, run `ssh vagrant@localhost -p 2222`, use `vagrant` as a password, and add that public key text to authorized_keys2 file. Shut down the VM, and `vagrant up` it again and it should connect.

**Comment by PurpleBooth** [comment]
Can I recommend you move away from Puphpet? Their puppet files are a massive mess, and it doesn't do anything that you can't do in a few lines of bash.

Obviously if DevOps is outside your comfort zone I can see why you'd want to keep it, but I'd strongly recommend moving to something else.

I can submit a PR showing how to do that if you'd like (or even a few very simple ansible files if you don't like bash).

**Comment by dragonmantank** [comment]
As long as we can get a good working PHP basebox to work with, I don't mind if we move away from puphpet. While I prefer puppet as a config management personally, we aren't using these puppet files on the deployment servers at all, so moving to Ansible or something else is fine with me. I haven't had time to replace the puphpet config files with a much simpler puppet config, as puphpet "works" most of the time.

The only main requirement I have is that the basebox use Ubuntu 14.04 64bit. Other than that we are using PHP and MySQL since this is a pretty basic Silex application.

**Comment by dragonmantank** [comment]
Replaced this with a Scotchbox-based basebox, so the auth bug should now be gone.
