### ISSUE TITLE
(doc) Add a code of conduct

### ISSUE THREAD

**Issue by PurpleBooth** [phpmentoring/testapp#64]
[Contributor Covenant - a code of conduct for open source projects.](http://contributor-covenant.org/)

> Open Source has always been a foundation of the Internet, and with the advent of social open source networks this is more true than ever. But open source projects suffer from a startling lack of diversity of participants, including women, people of color, and other underrepresented populations.
> 
> Part of this problem lies with the projects themselves. Insensitive language, thoughtless use of pronouns, projects with sexualized or culturally inappropriate names, and side effects of the pervasive cult of meritocracy make contributing to open source a daunting prospect for many people.
> ## A Small Step Forward
> 
> An easy way to begin addressing this problem is to be overt in our openness, welcoming all people to contribute, and pledging in return to value them as human beings and to foster an atmosphere of kindness, cooperation, and understanding.
> 
> The Contributor Covenant can be one way to express these values. Pledge your respect and appreciation for contributors and participants in your open source project by adding an explicit CODE_OF_CONDUCT.md to your project repository.

**Comment by dragonmantank** [comment]
Closing as we merged in the CoC
