### ISSUE TITLE
Add timezone based filtering

### ISSUE THREAD

**Issue by PurpleBooth** [phpmentoring/testapp#65]
It would be useful to identify mentors that are in the same timezone as you.

Arranging mentoring meetings can be tricky if neither of you are online at the same time. It would be better to be able to identify mentees and mentors that are within of a few hours of each other. This would ensure that you worked with people who are up at the same time as you.

I have added a PR (#63) that adds this information to the users profile. The exact mechanics of the search probably need to be discussed though, is it a time range, or do we relative choice from the users own timezone.

Opinions?

**Comment by dragonmantank** [comment]
Merged in the PR, so closing!
