### ISSUE TITLE
Change order of "Search Mentors"

### ISSUE THREAD

**Issue by Xethron** [phpmentoring/testapp#66]
Going to ["Search Mentors"](http://app.phpmentoring.org/mentors), you get a list of all mentors, from the first registered up to the last.

The first few times I viewed the list, I read it from top down, and only did the first few. This means the first few members will always get the most exposure.

I think the list should be swapped around, starting with the newest members, or be randomized, so that its in a different order every time you open it.

Let me know your thoughts, I'll be more than happy to make the changes.

**Comment by tdutrion** [comment]
There are two other features that are being developed and could be related: listing pairs and geolocation.

In this case, when both are developed and shipped, it would probably make sense to sort the paired mentors last, and bring near non-paired mentors on top. It would probably be better than just a random sort.

For now though, there are no sorting at all, so random sounds definitely better than nothing.

**Comment by dragonmantank** [comment]
I'm fine with randomizing the list, and would probably just randomize it in Angular so that once we get the JSON response back we scamble it up. That way each page load is different, but once the user starts subsetting the results they stay in the same order.

**Comment by dragonmantank** [comment]
This was randomized with #77, so closing
