### ISSUE TITLE
Vagrant Not working / can't auth

### ISSUE THREAD

**Issue by svpernova09** [phpmentoring/testapp#75]
Tried all the usual fixes, couldn't get anything to work, vagrant is unusable for me.

Vagrant 1.7.4
VirtualBox 5.0.14 r105127

Vagrant up log:

```
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'puphpet/debian75-x64' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Loading metadata for box 'puphpet/debian75-x64'
    default: URL: https://atlas.hashicorp.com/puphpet/debian75-x64
==> default: Adding box 'puphpet/debian75-x64' (v20151201) for provider: virtualbox
    default: Downloading: https://atlas.hashicorp.com/puphpet/boxes/debian75-x64/versions/20151201/providers/virtualbox.box
==> default: Successfully added box 'puphpet/debian75-x64' (v20151201) for 'virtualbox'!
==> default: Importing base box 'puphpet/debian75-x64'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'puphpet/debian75-x64' is up to date...
==> default: Setting the name of the VM: webapp_default_1460412244709_48733
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 80 => 8080 (adapter 1)
    default: 1080 => 1080 (adapter 1)
    default: 3306 => 7512 (adapter 1)
    default: 22 => 2222 (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
    default:
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default:
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.
```

**Comment by dragonmantank** [comment]
I have a change incoming that switches to Scotchbox.

In the meantime, you can ssh into the box using vagrant as both the
username and password, and 127.0.0.1:2222

On Monday, April 11, 2016, Joe Ferguson notifications@github.com wrote:

> Tried all the usual fixes, couldn't get anything to work, vagrant is
> unusable for me.
> 
> Vagrant 1.7.4
> VirtualBox 5.0.14 r105127
> 
> Vagrant up log:
> 
> Bringing machine 'default' up with 'virtualbox' provider...
> ==> default: Box 'puphpet/debian75-x64' could not be found. Attempting to find and install...
>     default: Box Provider: virtualbox
>     default: Box Version: >= 0
> ==> default: Loading metadata for box 'puphpet/debian75-x64'
>     default: URL: https://atlas.hashicorp.com/puphpet/debian75-x64
> ==> default: Adding box 'puphpet/debian75-x64' (v20151201) for provider: virtualbox
>     default: Downloading: https://atlas.hashicorp.com/puphpet/boxes/debian75-x64/versions/20151201/providers/virtualbox.box
> ==> default: Successfully added box 'puphpet/debian75-x64' (v20151201) for 'virtualbox'!
> ==> default: Importing base box 'puphpet/debian75-x64'...
> ==> default: Matching MAC address for NAT networking...
> ==> default: Checking if box 'puphpet/debian75-x64' is up to date...
> ==> default: Setting the name of the VM: webapp_default_1460412244709_48733
> ==> default: Clearing any previously set network interfaces...
> ==> default: Preparing network interfaces based on configuration...
>     default: Adapter 1: nat
>     default: Adapter 2: hostonly
> ==> default: Forwarding ports...
>     default: 80 => 8080 (adapter 1)
>     default: 1080 => 1080 (adapter 1)
>     default: 3306 => 7512 (adapter 1)
>     default: 22 => 2222 (adapter 1)
> ==> default: Running 'pre-boot' VM customizations...
> ==> default: Booting VM...
> ==> default: Waiting for machine to boot. This may take a few minutes...
>     default: SSH address: 127.0.0.1:2222
>     default: SSH username: vagrant
>     default: SSH auth method: private key
>     default: Warning: Connection timeout. Retrying...
>     default:
>     default: Vagrant insecure key detected. Vagrant will automatically replace
>     default: this with a newly generated keypair for better security.
>     default:
>     default: Inserting generated public key within guest...
>     default: Removing insecure key from the guest if it's present...
>     default: Key inserted! Disconnecting and reconnecting using new SSH key...
>     default: Warning: Authentication failure. Retrying...
>     default: Warning: Authentication failure. Retrying...
>     default: Warning: Authentication failure. Retrying...
>     default: Warning: Authentication failure. Retrying...
>     default: Warning: Authentication failure. Retrying...
>     default: Warning: Authentication failure. Retrying...
>     default: Warning: Authentication failure. Retrying...
>     default: Warning: Authentication failure. Retrying...
>     default: Warning: Authentication failure. Retrying...
>     default: Warning: Authentication failure. Retrying...
>     default: Warning: Authentication failure. Retrying...
>     default: Warning: Authentication failure. Retrying...
>     default: Warning: Authentication failure. Retrying...
>     default: Warning: Authentication failure. Retrying...
>     default: Warning: Authentication failure. Retrying...
>     default: Warning: Authentication failure. Retrying...
>     default: Warning: Authentication failure. Retrying...
>     default: Warning: Authentication failure. Retrying...
>     default: Warning: Authentication failure. Retrying...
>     default: Warning: Authentication failure. Retrying...
>     default: Warning: Authentication failure. Retrying...
>     default: Warning: Authentication failure. Retrying...
>     default: Warning: Authentication failure. Retrying...
>     default: Warning: Authentication failure. Retrying...
>     default: Warning: Authentication failure. Retrying...
>     default: Warning: Authentication failure. Retrying...
>     default: Warning: Authentication failure. Retrying...
>     default: Warning: Authentication failure. Retrying...
>     default: Warning: Authentication failure. Retrying...
> Timed out while waiting for the machine to boot. This means that
> Vagrant was unable to communicate with the guest machine within
> the configured ("config.vm.boot_timeout" value) time period.
> 
> If you look above, you should be able to see the error(s) that
> Vagrant had when attempting to connect to the machine. These errors
> are usually good hints as to what may be wrong.
> 
> If you're using a custom box, make sure that networking is properly
> working and you're able to connect to the machine. It is a common
> problem that networking isn't setup properly in these boxes.
> Verify that authentication configurations are also setup properly,
> as well.
> 
> If the box appears to be booting properly, you may want to increase
> the timeout ("config.vm.boot_timeout") value.```
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/phpmentoring/webapp/issues/75

## 

Chris Tankersley
http://ctankersley.com

**Comment by svpernova09** [comment]
I can SSH with credentials, but unable to provision the box.

**Comment by svpernova09** [comment]
If you're going to switch to scotchbox why not Laravel's Homestead? Per project install was built exactly for this :D

**Comment by dragonmantank** [comment]
The Scotchbox version is now in master. Any issues related to that can be new issues.
