### ISSUE TITLE
Bug: Unable to Search Mentors

### ISSUE THREAD

**Issue by elstamey** [phpmentoring/testapp#83]
On this page:  http://php-mentoring.org/mentors

This is happening:

![screen shot 2016-06-19 at 8 47 26 pm](https://cloud.githubusercontent.com/assets/4660760/16180867/1d25023e-365f-11e6-83c2-60c0e26c7cb9.png)

**Comment by dragonmantank** [comment]
That normally flashes up on the page load, but then should load with the full mentor list once the API returns the list of mentors.

What browser and OS are you using?

**Comment by elstamey** [comment]
Sorry I delayed in answering,  I think it was an issue with the API not loading the data, but it's definitely working now.
