### ISSUE TITLE
Upgrade Silex to the latest version (2.x)

### ISSUE THREAD

**Issue by dragonmantank** [phpmentoring/testapp#89]
We are using an older version of Silex. This should be updated, as the components have fallen quite far behind.

**Comment by christickner** [comment]
Are you working on this already @dragonmantank ? I could take a stab if not.

**Comment by dragonmantank** [comment]
Yup, started it last night. Trying to integrate new things lead me to finally biting the bullet and doing it :/

**Comment by christickner** [comment]
Ok cool. I'll hop onto some of the older issues.

**Comment by dragonmantank** [comment]
#93 was merged and deployed to Production. Closing!
