### ISSUE TITLE
Add docker-compose file to allow easier Docker development

### ISSUE THREAD

**Issue by dragonmantank** [phpmentoring/testapp#94]
We currently support local development as well as a Vagrant box, we should add Docker support as well. 

Blocking until #89 and #92 are finished.

**Comment by jmichaelward** [comment]
Hey @dragonmantank - just poking my head into this project, seeing where things are at. It looks like #89 and #92 were completed, so is this still blocked?

**Comment by dragonmantank** [comment]
Nope, unblocked now.
